name: Deploy
on: 
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "main.py"
          target: "/var/www/html/"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: ls
      
      - name: Run deployment.sh 
        run: bash deployment.sh

